---
- name: Restart deployments when a Secret changes
  hosts: localhost
  sources:
    - juniper.eda.k8s:
        api_version: v1
        kind: Secret
        namespace: "{{ project }}"
        name: demo-secret
  rules:
    - name: Secret modified -> restart selected deployments
      condition: event.type == "MODIFIED"
      action:
        run_job_template:
          name: restart-deployments-on-secret-modified
          organization: "Default"
          inventory: "EDA-Local"
          extra_vars:
            project: "{{ project }}"
            namespace: "{{ project }}"

