- name: Restart deployments when a Secret changes
  hosts: localhost
  sources:
    - ansible.eda.kubernetes:
        api_server: "https://kubernetes.default.svc:443"   # this URL because running inside openshift
        api_key: "{{ lookup('env','K8S_AUTH_API_KEY') }}"
        verify_ssl: true
        kind: Secret
        namespace: "{{ namespace }}"
        name: demo-secret
        event: modified
  rules:
    - name: Secret modified -> restart selected deployments
      condition: event is defined
      action:
        run_playbook:
          name: playbooks/restart-deployments-using-secret.yml
          organization: "Default"          # <-- your org
          inventory: "EDA-Local"           # <-- the inventory you created
          extra_vars:
            namespace: "{{ namespace }}"
            secret_name: demo-secret
            restart_label: "restart-on=demo-secret"
