- name: Restart deployments when a Secret changes
  hosts: localhost
  sources:
    - juniper.eda.k8s:
        kind: Secret
        namespace: "{{ namespace }}"
        name: demo-secret
        event: modified
  rules:
    - name: Secret modified -> restart selected deployments
      condition: event is defined
      action:
        run_job_template:
          name: restart-deployments-on-secret-modified
          organization: "Default"
          inventory: "EDA-Local"
          extra_vars:
            namespace: "{{ namespace }}"

