- name: Hello when payload present
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: say hello if payload
      condition: event.payload is defined
      action:
        debug:
          msg: "hello"

