- name: Hello via webhook
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000           # listener inside the activation
  rules:
    - name: say hello on any event
      condition: event is defined
      action:
        debug:
          msg: "hello"
