---
- name: Restart deployments on Secret modified
  hosts: localhost
  gather_facts: false
  vars:
    project: "{{ project }}"
  tasks:
    - name: Get deployments with the restart label
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        namespace: "{{ project }}"
        label_selectors:
          - restart-on=demo-secret
      register: deployments

    - name: Restart deployments by patching annotation
      kubernetes.core.k8s:
        api_version: apps/v1
        kind: Deployment
        name: "{{ item.metadata.name }}"
        namespace: "{{ project }}"
        merge_type: strategic-merge
        definition:
          spec:
            template:
              metadata:
                annotations:
                  secret-restart-timestamp: "{{ lookup('pipe', 'date +%s') }}"
      loop: "{{ deployments.resources }}"
      when: deployments.resources | length > 0