---
- name: Restart deployments on Secret modified
  hosts: localhost
  gather_facts: false
  vars:
    namespace: "{{ namespace }}"
    secret_name: "{{ secret_name }}"
    restart_label: "{{ restart_label | default('restart-on=secret/' ~ secret_name) }}"
  tasks:
    - name: Get deployments with the restart label
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        namespace: "{{ namespace }}"
        label_selectors:
          - "{{ restart_label }}"
      register: deployments

    - name: Restart deployments by patching annotation
      kubernetes.core.k8s:
        api_version: apps/v1
        kind: Deployment
        name: "{{ item.metadata.name }}"
        namespace: "{{ namespace }}"
        merge_type: strategic-merge
        definition:
          spec:
            template:
              metadata:
                annotations:
                  secret-restart-timestamp: "{{ lookup('pipe', 'date +%s') }}"
      loop: "{{ deployments.resources }}"
      when: deployments.resources | length > 0